import Loam.Observations.Observation194

namespace Loam.Observation195

set_option autoImplicit false

/-!
# Observation 195 — semantic result observation

Observation 194 showed that future Correction can change not only a projected
quantity but whether the selected semantic question is answerable at all. Its
concrete observer already returned `Option Int`:

```text
some quantity  = admitted semantic answer
none           = fail-closed refusal
```

Before adding a new result framework, this observation checks whether the
existing mathematics from Observations 191 and 192 already treats such
fail-closed definedness correctly.

The key fact is easy to miss: Observation 191 already permits an arbitrary,
observation-dependent result type, and Observation 192 permits an arbitrary
answer type. `Option`, `Except Refusal`, or another explicit semantic-result type
can therefore live in the observation codomain without changing the quotient
construction itself.

This field trial uses `Option` because that is the actual result shape exposed by
`CorrectionFrontier` in Observations 193–194. It asks two narrower questions:

1. Does exact semantic-result observation determine availability as a derived
   observation through the Observation-191 quotient?
2. Is availability alone strictly coarser than the exact semantic result?
-/

universe uS uQ uA uO

section Generic

variable {State : Type uS}
variable {Question : Type uQ}
variable {Answer : Type uA}
variable {Operation : Type uO}

/--
Observe either the exact semantic result or only whether that result is defined.
The latter deliberately forgets the payload.
-/
inductive SemanticObservable (Question : Type uQ) where
  | result : Question → SemanticObservable Question
  | available : Question → SemanticObservable Question
  deriving Repr

/-- The result type depends on which observation is being asked. -/
def SemanticValue (Answer : Type uA) : SemanticObservable Question → Type uA
  | .result _ => Option Answer
  | .available _ => Bool

/-- Lift an `Option`-valued semantic observer with its derived availability view. -/
def semanticObserve
    (answer : State → Question → Option Answer)
    (observable : SemanticObservable Question)
    (state : State) : SemanticValue (Question := Question) Answer observable :=
  match observable with
  | .result question => answer state question
  | .available question => (answer state question).isSome

/-- Select exact semantic results for the visible question vocabulary. -/
def ExactResultBasis
    (vocabulary : Loam.Observation029.Vocabulary Question) :
    SemanticObservable Question → Prop
  | .result question => vocabulary question
  | .available _ => False

/-- Select only availability, deliberately forgetting successful payloads. -/
def AvailabilityBasis
    (vocabulary : Loam.Observation029.Vocabulary Question) :
    SemanticObservable Question → Prop
  | .result _ => False
  | .available question => vocabulary question

/--
Availability is a post-processing of the exact semantic result, so it is
constant on every equivalence class induced by that exact result.
-/
theorem availability_factors_through_exact_result
    (answer : State → Question → Option Answer)
    (vocabulary : Loam.Observation029.Vocabulary Question)
    (question : Question)
    (hVisible : vocabulary question) :
    Loam.Observation191.FactorsThroughIndistinguishability
      (semanticObserve answer)
      (ExactResultBasis vocabulary)
      (.available question) := by
  intro left right hIndistinguishable
  have hResult :=
    hIndistinguishable (.result question) hVisible
  change
    (answer left question).isSome =
      (answer right question).isSome
  exact congrArg Option.isSome hResult

/--
By Observation 191's all-endomap theorem, availability therefore belongs to the
closure generated by the exact result observation.
-/
theorem availability_is_in_exact_result_closure
    (answer : State → Question → Option Answer)
    (vocabulary : Loam.Observation029.Vocabulary Question)
    (question : Question)
    (hVisible : vocabulary question) :
    Loam.Observation191.Closure
      (semanticObserve answer)
      (ExactResultBasis vocabulary)
      (.available question) :=
  (Loam.Observation191.closure_iff_factors_through_indistinguishability
    (semanticObserve answer)
    (ExactResultBasis vocabulary)
    (.available question)).2
      (availability_factors_through_exact_result
        answer vocabulary question hVisible)

/-- Project only semantic availability from an `Option`-valued observer. -/
def availabilityAnswer
    (answer : State → Question → Option Answer)
    (state : State)
    (question : Question) : Bool :=
  (answer state question).isSome

/--
Observation 192 already accepts `Option Answer` as its answer type. Exact
future-context equivalence therefore automatically preserves future semantic
availability, without a second dynamic quotient definition.
-/
theorem future_result_equivalence_implies_future_availability_equivalence
    (answer : State → Question → Option Answer)
    (step : State → Operation → State)
    (vocabulary : Loam.Observation029.Vocabulary Question)
    {left right : State}
    (h : Loam.Observation192.FutureEquivalent
      answer step vocabulary left right) :
    Loam.Observation192.FutureEquivalent
      (availabilityAnswer answer) step vocabulary left right := by
  intro continuation question hVisible
  exact congrArg Option.isSome (h continuation question hVisible)

/--
Conversely, one future availability difference is already enough to refute exact
future semantic-result equivalence. Observation 194 is precisely this shape with
`none` on one side and `some 0` on the other.
-/
theorem future_availability_difference_refutes_result_equivalence
    (answer : State → Question → Option Answer)
    (step : State → Operation → State)
    (vocabulary : Loam.Observation029.Vocabulary Question)
    (left right : State)
    (continuation : List Operation)
    (question : Question)
    (hVisible : vocabulary question)
    (hDifferent :
      availabilityAnswer answer
          (Loam.Observation192.run step left continuation) question ≠
        availabilityAnswer answer
          (Loam.Observation192.run step right continuation) question) :
    ¬ Loam.Observation192.FutureEquivalent
      answer step vocabulary left right := by
  intro hFuture
  apply hDifferent
  exact congrArg Option.isSome (hFuture continuation question hVisible)

end Generic

/-! ## Strictness: availability is genuinely coarser than exact result -/

inductive OneQuestion where
  | value
  deriving Repr

private def allQuestions :
    Loam.Observation029.Vocabulary OneQuestion :=
  fun _ => True

/-- Two states are both semantically available but return different values. -/
private def strictAnswer (state : Bool) : OneQuestion → Option Int
  | .value => if state then some 120 else some 100

/-- Availability-only observation merges the two states. -/
theorem availability_only_cannot_distinguish_values :
    Loam.Observation191.IndistinguishableBy
      (semanticObserve strictAnswer)
      (AvailabilityBasis allQuestions)
      false true := by
  intro observable hSelected
  cases observable with
  | result question =>
      simp [AvailabilityBasis] at hSelected
  | available question =>
      cases question
      simp [semanticObserve, strictAnswer]

/-- Exact result observation does distinguish those same states. -/
theorem exact_results_distinguish_values :
    ¬ Loam.Observation191.IndistinguishableBy
      (semanticObserve strictAnswer)
      (ExactResultBasis allQuestions)
      false true := by
  intro h
  have hResult := h (.result .value) (by simp [ExactResultBasis, allQuestions])
  simp [semanticObserve, strictAnswer] at hResult

/--
Equivalently, exact result does not factor through the quotient induced by
availability alone. Definedness is derived from result, but result is not derived
from definedness.
-/
theorem exact_result_does_not_factor_through_availability :
    ¬ Loam.Observation191.FactorsThroughIndistinguishability
      (semanticObserve strictAnswer)
      (AvailabilityBasis allQuestions)
      (.result .value) := by
  intro hFactors
  have hResult :=
    hFactors false true availability_only_cannot_distinguish_values
  simp [semanticObserve, strictAnswer] at hResult

/-!
## Finding

No new quotient machinery is needed for fail-closed semantic results.
Observation 191 already allows the observation codomain itself to carry
availability/refusal, and Observation 192 already compares arbitrary answer
values after future contexts.

For an `Option`-valued semantic question:

```text
exact semantic result
      |
      | post-process with Option.isSome
      v
semantic availability
```

Lean proves that availability factors through the exact-result observational
quotient and therefore lies in its Observation-191 closure. The converse fails:
two successful but unequal results (`some 100` and `some 120`) are identical to
availability-only observation.

So the information order is strict:

```text
exact result  ->  availability
     stronger      weaker
```

Observation 193 witnesses the value-sensitive side of this order. Observation
194 witnesses the availability-sensitive side after a real Correction future
context. Both are ordinary distinctions in the same future observational
quotient once the full semantic result is kept as the observation value.

This observation deliberately does not introduce a production `SemanticResult`
type. `CorrectionFrontier` currently exposes `Option`, and no evidence yet earns
refusal-reason identity as household semantics. If refusal reasons later become
observable, an `Except Refusal Answer` codomain fits the same generic
Observation-191/192 machinery without changing the quotient definitions.
-/

end Loam.Observation195
