cabal-version:      3.0
name:               loam-ui-prototype03
version:            0.0.0.1
synopsis:           Synthetic Brick interaction mechanics spike for LOAM
license:             MIT
build-type:          Simple

executable loam-ui-prototype03
    main-is:          Main.hs
    hs-source-dirs:   .
    default-language: Haskell2010
    ghc-options:      -Wall
    build-depends:    base >= 4.14 && < 5
                    , brick >= 1.0
                    , vty >= 6.0
                    , vty-crossplatform
