#!/usr/bin/env python3
"""
run-alloy-manifest.py — Manifest-driven Alloy runner for LOAM observations.

Executes Alloy models and verifies that the resulting SAT/UNSAT commands match
the expected receipt dictionary defined in tools/alloy_manifest.json.
"""

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

def parse_args():
    parser = argparse.ArgumentParser(description="Run Alloy observations from manifest.")
    parser.add_argument("--manifest", default="tools/alloy_manifest.json",
                        help="Path to manifest JSON (default: tools/alloy_manifest.json)")
    parser.add_argument("--alloy-jar", default=os.environ.get("ALLOY_JAR"),
                        help="Path to org.alloytools.alloy.dist.jar (or set ALLOY_JAR env var)")
    parser.add_argument("--id", help="Filter by specific observation ID(s), comma-separated")
    parser.add_argument("--model", help="Filter by specific model path")
    parser.add_argument("--changed-files", help="List of changed files (comma or space separated) to filter relevant models")
    parser.add_argument("--dry-run", action="store_true", help="Print cases that would run without executing Alloy")
    parser.add_argument("--verbose", action="store_true", help="Verbose output")
    return parser.parse_args()

def load_manifest(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)

def filter_cases(manifest, args):
    if args.id:
        target_ids = set(x.strip() for x in args.id.split(","))
        return [c for c in manifest if c["id"] in target_ids]
    if args.model:
        return [c for c in manifest if c["model"] == args.model]
    if args.changed_files:
        raw = args.changed_files.replace(",", " ").split()
        changed = set(x.strip() for x in raw if x.strip())
        # If manifest itself, run all
        if any("alloy_manifest.json" in f or "run-alloy-manifest.py" in f or "alloy-observations.yml" in f for f in changed):
            print("Notice: Manifest or runner script changed, running all cases.")
            return manifest
        # Otherwise filter by model path
        matched = [c for c in manifest if c["model"] in changed]
        return matched
    return manifest

def run_single_case(case, alloy_jar, verbose=False):
    model_path = case["model"]
    expected = case["expected"]
    case_id = case["id"]

    if not os.path.exists(model_path):
        return False, f"Model file not found: {model_path}"

    with tempfile.TemporaryDirectory(prefix=f"alloy_{case_id}_") as tmpdir:
        cmd = [
            "java", "-jar", alloy_jar,
            "exec", "-f", "-s", "sat4j",
            "-o", tmpdir,
            model_path
        ]
        if verbose:
            print(f"[{case_id}] Executing: {' '.join(cmd)}")

        proc = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
        if proc.returncode != 0 and not os.path.exists(os.path.join(tmpdir, "receipt.json")):
            return False, f"Alloy execution failed with code {proc.returncode}:\n{proc.stdout}"

        receipt_file = os.path.join(tmpdir, "receipt.json")
        if not os.path.exists(receipt_file):
            return False, f"receipt.json was not generated by Alloy:\n{proc.stdout}"

        try:
            with open(receipt_file, "r", encoding="utf-8") as rf:
                receipt = json.load(rf)
        except Exception as e:
            return False, f"Failed to parse receipt.json: {e}\nRaw output:\n{proc.stdout}"

        commands = receipt.get("commands", {})
        errors = []

        for name, want_sat in expected.items():
            sol = commands.get(name, {}).get("solution", [])
            is_sat = bool(sol)
            if is_sat != want_sat:
                got_str = "SAT" if is_sat else "UNSAT"
                want_str = "SAT" if want_sat else "UNSAT"
                errors.append(f"{name}: expected {want_str}, got {got_str}")
            elif verbose:
                label = "SAT" if is_sat else "UNSAT"
                print(f"  {name}: {label} (OK)")

        if errors:
            return False, f"Receipt assertion failure in {case_id}:\n  " + "\n  ".join(errors)

    return True, "OK"

def main():
    args = parse_args()
    manifest_path = Path(args.manifest)
    if not manifest_path.is_absolute():
        manifest_path = Path.cwd() / manifest_path

    if not manifest_path.exists():
        print(f"Error: Manifest not found: {manifest_path}", file=sys.stderr)
        sys.exit(1)

    manifest = load_manifest(manifest_path)
    selected = filter_cases(manifest, args)

    print(f"=== Alloy Manifest Runner ===")
    print(f"Total cases in manifest: {len(manifest)}")
    print(f"Selected cases to run:   {len(selected)}")

    if not selected:
        print("No cases matched filter. Nothing to do.")
        sys.exit(0)

    if args.dry_run:
        print("\n--- Dry Run (selected cases) ---")
        for i, c in enumerate(selected, 1):
            exp_summary = ", ".join(f"{k}={'SAT' if v else 'UNSAT'}" for k, v in c["expected"].items())
            print(f"[{i:3d}/{len(selected):3d}] {c['id']:40s} -> {c['model']} ({exp_summary})")
        print("\nDry run completed successfully.")
        sys.exit(0)

    if not args.alloy_jar or not os.path.exists(args.alloy_jar):
        print("Error: Alloy jar not found. Please provide --alloy-jar or set ALLOY_JAR env var.", file=sys.stderr)
        sys.exit(1)

    failed = []
    passed = 0

    print("\nStarting execution...")
    for i, c in enumerate(selected, 1):
        case_id = c["id"]
        print(f"[{i:3d}/{len(selected):3d}] Running {case_id} ({c['model']})... ", end="", flush=True)
        ok, msg = run_single_case(c, args.alloy_jar, verbose=args.verbose)
        if ok:
            print("PASS")
            passed += 1
        else:
            print("FAIL")
            print(f"  --> {msg}")
            failed.append((case_id, msg))

    print(f"\n=== Summary ===")
    print(f"Total: {len(selected)} | Passed: {passed} | Failed: {len(failed)}")

    if failed:
        print("\nFailed cases:")
        for cid, msg in failed:
            print(f"  - {cid}: {msg.splitlines()[0]}")
        sys.exit(1)
    else:
        print("\nAll selected Alloy observation checks PASSED!")
        sys.exit(0)

if __name__ == "__main__":
    main()
